### ISSUE TITLE
Provide example to access fonts in web page

### ISSUE THREAD

**Issue by martindsouza** [oracle/font-apex#1]
Font-Awesome has an example to quickly get started by using `<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">` Can you provide similar way to do this with Font-APEX?

_Note: Should also put on a CDN / not sure if that's already in the plans_

**Comment by shakeebr** [comment]
Hi Martin,

I updated the readme and the About page with some basic instructions on getting started. We don't yet have a CDN but that's a great idea!

Closing.
